MyBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.views.static import serve
from MyBlog import settings
from blog import views
urlpatterns = [
	path('admin/', admin.site.urls),
	path('blog/', include('blog.urls')),
	#     暴露服务器资源接口
	re_path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

blog/urls.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-
# ！python3.9.10
# @Time    : 2022/11/3 15:57
# @Author  : 妙玄
# @File    : urls.py
from django.urls import path,re_path
from blog import views
urlpatterns = [
    path('home/', views.index, name='home'),
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    # 后台管理
    path('backend/', views.backend, name='backend'),
    # 添加文章
    path('add_article', views.add_article, name='add_article'),
    # 图片验证码
    path('get_code/',views.get_code, name='get_code'),
    path('set_password/',views.set_password, name='set_password'),
    path('logout/', views.logout, name='logout'),
    # 编辑器上传图片接口
    path('upload_image/', views.upload_image, name='upload_image'),
    # 修改用户头像
    path('set_avatar/', views.set_avatar, name='set_avatar'),
    re_path(r'^comment/', views.comment, name='comment'),
#     点赞点踩
    re_path(r'^up_or_down/$', views.up_or_down, name='up_or_down'),
# 个人站点页面搭建
    re_path(r'^(?P<username>\w+)/$', views.site, name='site'),
#     侧边栏筛选针对article_list再次筛选
#     re_path(r'(?P<username>\w+)/category/(\d+)', views.site),# 分类
#     re_path(r'(?P<username>\w+)/tag/(\d+)', views.site), # 标签
#     re_path(r'(?P<username>\w+)/archive/(\w+)', views.site) # 标签
    re_path(r'^(?P<username>\w+)/(?P<condition>category|tag|archive)/(?P<param>.*)/', views.site),
#     文章详情页
    re_path(r'^(?P<username>\w+)/article/(?P<article_id>\d+)', views.article_detail)
]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


# 1. 先写普通字段
class UserInfo(AbstractUser):
	phone = models.BigIntegerField(verbose_name='手机号', null=True, blank=True)
	'''
	给avatar字段存储文件对象，该文件会自动存储到avatar文件夹下，然后avatar字段的值保存文件路径
	'''
	avatar = models.FileField(verbose_name='头像', upload_to='avatar/', default='avatar/default.png')
	create_time = models.DateField(auto_now_add=True)
	blog = models.OneToOneField(to='Blog', null=True, on_delete=models.CASCADE)
	class Meta:
		db_table = 'UserInfo'
		verbose_name_plural = '用户'
	def __str__(self):
		return self.username
# 个人站点
class Blog(models.Model):
	site_name = models.CharField(verbose_name='站点名称', max_length=32)
	site_title = models.CharField(verbose_name='站点标题', max_length=32)
	site_theme = models.CharField(verbose_name='站点样式', max_length=64, null=True)  # 村css或js的文件路径，简单模拟
	class Meta:
		db_table = 'Blog'
		verbose_name_plural = '站点'
	def __str__(self):
		return self.site_name
# 文章分类
class Category(models.Model):
	name = models.CharField(verbose_name='分类名', max_length=32)
	blog = models.ForeignKey(to='Blog', null=True, on_delete=models.CASCADE)
	class Meta:
		db_table = 'Category'
		verbose_name_plural = '文章分类'
		
	def __str__(self):
		return self.name
# 文章标签
class Tag(models.Model):
	name = models.CharField(verbose_name='标签名', max_length=32)
	blog = models.ForeignKey(to='Blog', null=True, on_delete=models.CASCADE)
	class Meta:
		db_table = 'Tag'
		verbose_name_plural = '文章标签'
	def __str__(self):
		return self.name
# 文章
class Article(models.Model):
	title = models.CharField(verbose_name='文章标题', max_length=64)
	desc = models.CharField(verbose_name='文章简介', max_length=255)
	content = models.TextField(verbose_name='文章内容')
	create_time = models.DateField(auto_now_add=True)
	# 	数据库字段设计优化
	up_num = models.IntegerField(verbose_name='点赞数', default=0)
	down_num = models.IntegerField(verbose_name='点踩数', default=0)
	comment_num = models.IntegerField(verbose_name='评论数', default=0)
	
	blog = models.ForeignKey(to='Blog', null=True, on_delete=models.CASCADE)
	category = models.ForeignKey(to='Category', null=True, on_delete=models.CASCADE)
	tags = models.ManyToManyField(to='Tag', through='ArticleToTag', through_fields=('article', 'tag'))
	class Meta:
		db_table = 'Article'
		verbose_name_plural = '文章'
	def __str__(self):
		return self.title
# 点赞表
class UpAndDown(models.Model):
	user = models.ForeignKey(to='UserInfo', on_delete=models.CASCADE)
	article = models.ForeignKey(to='Article', on_delete=models.CASCADE)
	is_up = models.BooleanField(default=True)
	class Meta:
		db_table = 'UpAndDown'
		verbose_name_plural = '点赞'
# 评论表
class Comment(models.Model):
	user = models.ForeignKey(to='UserInfo', on_delete=models.CASCADE)
	article = models.ForeignKey(to='Article', on_delete=models.CASCADE)
	content = models.CharField(verbose_name='评论内容', max_length=255)
	comment_time = models.DateTimeField(verbose_name='评论时间', auto_now_add=True)
	# 	自关联
	parent = models.ForeignKey(verbose_name='子评论', to='self', null=True, on_delete=models.CASCADE)
	class Meta:
		db_table = 'Comment'
		verbose_name_plural = '评论'
class ArticleToTag(models.Model):
	article = models.ForeignKey(to='Article', on_delete=models.CASCADE)
	tag = models.ForeignKey(to='Tag', on_delete=models.CASCADE)
	class Meta:
		db_table = 'ArticleToTag'
		verbose_name_plural = '文章与标签'

blog/views.py
# -*- coding: UTF-8 -*-
import json
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.shortcuts import HttpResponseRedirect
from blog import myforms
from blog import models
from django.http import JsonResponse
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont
import random
from io import BytesIO
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.db.models.functions import TruncMonth
from django.db.models import F
from django.db import transaction
from utils import mypage
from bs4 import BeautifulSoup
import os
from MyBlog import settings
# Create your views here.

def register(request):
	form_obj = myforms.MyRegForm()
	if request.method == 'POST':
		# 检验数据是否合法
		back_dic = {'code': 1000, 'msg': ''}
		form_obj = myforms.MyRegForm(request.POST)
		# 判断数据是否合法
		if form_obj.is_valid():
			clean_data = form_obj.cleaned_data
			clean_data.pop('re_password')
			# 用户头像
			avatar = request.FILES.get('avatar')
			print(avatar)
			# 针对用户头像做空值判断
			if avatar:
				clean_data['avatar'] = avatar
			print(clean_data)
			# 操作数据库导入数据
			models.UserInfo.objects.create_user(**clean_data)
			back_dic['url'] = '/blog/login/'
		else:
			back_dic['code'] = 2000
			back_dic['msg'] = form_obj.errors
		return JsonResponse(back_dic)  # 前端args接收back_dic
	return render(request, 'blog/register.html', locals())
def index(request):
	article_queryset = models.Article.objects.all()
	return render(request, 'blog/index.html', locals())
def get_random():
	return random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)
def get_code(request):
	img_obj = Image.new('RGB', (300, 45), get_random())
	img_draw = ImageDraw.Draw(img_obj)
	img_font = ImageFont.truetype('blog/static/font/思源宋体TW-SemiBold.otf', 30)
	# 	随机验证码
	code = ''
	for i in range(6):
		random_upper = chr(random.randint(65, 90))
		random_lower = chr(random.randint(97, 122))
		random_int = str(random.randint(0, 9))
		tmp = random.choice([random_int, random_lower, random_upper])
		img_draw.text((i * 50 + 18, 0), tmp, get_random(), img_font)
		code += tmp
	request.session['code'] = code
	io_obj = BytesIO()
	img_obj.save(io_obj, format='png')
	image_stream = io_obj.getvalue()
	return HttpResponse(image_stream, content_type="image/png")
def login(request):
	if request.method == 'POST':
		# 正对Ajax请求，通常会定义一个字典
		back_dic = {'code': 1000, 'msg': ''}
		username = request.POST.get('username')
		password = request.POST.get('password')
		code = request.POST.get('code')
		print(code, username, password)
		# 1. 先校验验证码
		if request.session.get('code') == code:
			user_obj = auth.authenticate(request, username=username, password=password)
			if user_obj:
				# 			保存用户状态
				auth.login(request, user_obj)
				back_dic['url'] = '/blog/home/'
			else:
				back_dic['code'] = 2000
				back_dic['msg'] = '用户名或密码错误'
		else:
			back_dic['code'] = 3000
			back_dic['msg'] = '验证码错误'
		return JsonResponse(back_dic)
	return render(request, 'blog/login.html')
@login_required()
def set_password(request):
	if request.is_ajax():
		back_dic = {'code': 1000, 'msg': ''}
		if request.method == 'POST':
			old_password = request.POST.get('old_password')
			new_password = request.POST.get('new_password')
			confirm_password = request.POST.get('confirm_password')
			# print(old_password, new_password, confirm_password)
			if request.user.check_password(old_password):
				if new_password == confirm_password:
					request.user.set_password(new_password)
					request.user.save()
					back_dic['msg'] = '修改成功'
				else:
					back_dic['code'] = 1001
					back_dic['msg'] = '两次密码不一致'
			else:
				back_dic['code'] = 1002
				back_dic['msg'] = '原密码不正确'
		return JsonResponse(back_dic)

def site(request, username, **kwargs):
	"""
	如果**kwargs有值，需要对article_list做额外的操作
	"""
	user_obj = models.UserInfo.objects.filter(username=username).first()
	# 用户如果不存在，返回404页面
	if not user_obj:
		return render(request, 'blog/errors.html')
	blog = user_obj.blog
	article_list = models.Article.objects.filter(blog=blog)
	if kwargs:
		# print(kwargs)  # {'condition': 'tag', 'param': '1'}
		condition = kwargs.get('condition')
		param = kwargs.get('param')
	# 	判断用户按哪个条件进行筛选
		if condition == 'category':
			article_list = article_list.filter(category_id=param)
		elif condition == 'tag':
			article_list = article_list.filter(tags__id=param)
		else:
			year, month = param.split('-')
			article_list = article_list.filter(create_time__year=year, create_time__month=month)
	# 查询当前用户所有的分类以及分类下的文章数
	category_list = models.Category.objects.filter(blog=blog).annotate(count_num=Count('article__pk')).values_list('name', 'count_num', 'pk')
	# print(category_list)
	# 查询当前用户所有的标签以及标签下的文章数
	tag_list = models.Tag.objects.filter(blog=blog).annotate(count_num=Count('article__pk')).values_list('name', 'count_num', 'pk')
	# print(tag_list)
	# 按照年月分组查询所有文章
	date_list = models.Article.objects.filter(blog=blog).annotate(month=TruncMonth('create_time')).values('month').annotate(count_num=Count('pk')).values_list('month', 'count_num')
	# print(date_list)
	return render(request, 'blog/site.html', locals())
#  侧边栏筛选针对article_list再次筛选
def article_detail(request, username, article_id):
	user_obj = models.UserInfo.objects.filter(username=username).first()
	blog = user_obj.blog
	# 先获取文章对象
	article_boj = models.Article.objects.filter(pk=article_id, blog__userinfo__username=username).first()
	if not article_boj:
		return render(request, 'blog/errors.html')
	# 获取当前文章的所有评论
	comment_list = models.Comment.objects.filter(article=article_boj)
	return render(request, 'blog/article_detail.html', locals())

def up_or_down(request):
	if request.is_ajax():
		back_dic = {'code':1000, 'msg':''}
		# print(back_dic)
		if request.user.is_authenticated:
			article_id = request.POST.get('article_id')
			is_up = request.POST.get('is_up')
			is_up = json.loads(is_up)
			article_obj = models.Article.objects.filter(pk=article_id).first()
			if not article_obj.blog.userinfo == request.user:
		# 		校验当前用户是否已经点赞了
				is_click = models.UpAndDown.objects.filter(user=request.user, article=article_obj)
		# 		操作数据库，记录数据，同步操作
				if not is_click:
					if is_up:
			# 			给点赞数加1
						models.Article.objects.filter(pk=article_id).update(up_num=F('up_num')+1)
						back_dic['msg'] = '谢谢点赞'
					else:
			# 			给点踩数加1
						models.Article.objects.filter(pk=article_id).update(up_num=F('down_num') + 1)
						back_dic['msg'] = '不要踩我'
					models.UpAndDown.objects.create(user=request.user, article=article_obj, is_up=is_up)
				else:
					back_dic['code'] = 1001
					back_dic['msg'] = '不可重复点赞'
			else:
				back_dic['code'] = 1002
				back_dic['msg'] = '不能给自己的文章点赞'
		else:
			back_dic['code'] = 1003
			back_dic['msg'] = '请先登录'
		return JsonResponse(back_dic)
def comment(request):
	if request.is_ajax():
		back_dic = {'code': 1000, 'msg': ''}
		if request.method == 'POST':
			if request.user.is_authenticated:
				article_id = request.POST.get('article_id')
				content = request.POST.get('content')
				parent_id = request.POST.get('parent_id')
				print(parent_id)
	# 			直接操作评论表存储数据，两张表，开启事务
				with transaction.atomic():
					models.Article.objects.filter(pk = article_id).update(comment_num = F('comment_num') + 1)
					models.Comment.objects.create(user=request.user, article_id=article_id, content=content, parent_id=parent_id)
				back_dic['msg'] = '感谢评论'
			else:
				back_dic['code'] = 1001
				back_dic['msg'] = ['用户未登录']
			# print(back_dic)
			return JsonResponse(back_dic)
def logout(request):
	response = render(request, 'blog/login.html')
	response.delete_cookie(key='sessionid')
	return response

@login_required
def backend(request):
	
	article_list = models.Article.objects.filter(blog=request.user.blog)
	page_obj = mypage.Pagination(current_page=request.GET.get('page', 1), all_count=article_list.count(), per_page_num=10)
	page_queryset = article_list[page_obj.start:page_obj.end]
	return render(request, 'backend/backend.html', locals())


@login_required
def add_article(request):
	if request.method == 'POST':
		title = request.POST.get('title')
		content = request.POST.get('content')
		category_id = request.POST.get('category')
		tag_id_list = request.POST.getlist('tag')
		soup = BeautifulSoup(content, 'html.parser')
		tags = soup.find_all()
		for tag in tags:
			print(tag.name)# 获取页面所有标签
			if tag.name == 'script':
				tag.decomposed()
	# 	文章简介：切取content的前150字符
		desc = soup.text[0:150]
		# desc = content[0:150]
		article_obj = models.Article.objects.create(title=title, content=str(soup),desc=desc, category_id=category_id, blog=request.user.blog)
		article_obj_list = []
		for i in tag_id_list:
			article_obj_list.append(models.ArticleToTag(article=article_obj, tag_id=i))
		models.ArticleToTag.objects.bulk_create(article_obj_list)
		return HttpResponseRedirect('/blog/backend/')
	category_list = models.Category.objects.filter(blog=request.user.blog)
	tag_list = models.Tag.objects.filter(blog=request.user.blog)
	return render(request, 'backend/add_article.html', locals())


def upload_image(request):
	back_dic = {'error': 0}  # 先提前定义返回给编辑器的数据格式
	if request.method == 'POST':
	# 	获取用户上传的图片对象
		file_obj = request.FILES.get('imgFile')
		file_dir = os.path.join(settings.BASE_DIR, 'media', 'article_image')
	# 	先判断该文件夹是否存在，如果不存在，自动创建
		if not os.path.isdir(file_dir):
			os.mkdir(file_dir)
	# 	拼接图片的完整路径
		file_path = os.path.join(file_dir, file_obj.name)
		with open(file_path, 'wb')as f:
			for line in file_obj:
				f.write(line)
		back_dic['url'] = '/media/article_image/%s'%file_obj.name
	return JsonResponse(back_dic)

@login_required
def set_avatar(request):
	if request.method == 'POST':
		file_obj = request.FILES.get('avatar')
		# models.UserInfo.objects.filter(pk=request.user.pk).update(avatar=file_obj) 不会自己加avatar前缀
	# 	1. 手动添加前缀
	#  2.
		user_obj = request.user
		user_obj.avatar = file_obj
		user_obj.save()
		return HttpResponseRedirect('/blog/home/')
	blog = request.user.blog

blog/templates/backend/add_article.html
{% extends 'backend/base.html' %}
{% block article %}
    文章添加页面
    <h3>添加文章</h3>
    {#    直接利用form表单添加数据#}
    <form action="" method="post">
        <p>标题</p>
        <div>
            <input type="text" name="title" class="form-control">
        </div>
        <p>内容</p>
        <textarea name="content" id="id_content" cols="30" rows="10">
        </textarea>
        <p>分类</p>
        <div>
            {% for category in category_list %}
                <input type="radio" value="{{ category.pk }}" name="category">{{ category.name }}
            {% endfor %}
        </div>
        <p>标签</p>
        {% for tag in tag_list %}
            <input type="checkbox" value="{{ tag.pk }}" name="tag">{{ tag.name }}
        {% endfor %}
        <br><input type="submit" class="btn btn-success">
        {#富文本编辑器#}
    </form>
{% endblock %}

blog/templates/backend/backend.html
{% extends 'backend/base.html' %}
{% block article %}
    <table class="table table-hover table-striped table-bordered">
        <thead>
        <tr>
            <th>标题</th>
            <th>评论数</th>
            <th>点赞数</th>
            <th>操作项</th>
            <th>操作项</th>
        </tr>
        </thead>
        <tbody>

        {% for article in page_queryset %}
            <tr>
                <td><a href="/blog/{{ request.user.username }}/article/{{ article.pk }}">{{ article.title }}</a></td>
                <td>{{ article.comment_num }}</td>
                <td>{{ article.up_num }}</td>
                <td><a href="">编辑</a></td>
                <td><a href="">删除</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pull-right">
        {{ page_obj.page_html|safe }}
    </div>
{% endblock %}

blog/templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script charset="utf-8" src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#id_content', {
                width: '100%',
                height: '450px',
                resizeType:1,
                uploadJson : '/blog/upload_image/',//上传图片的后端提交路径
                extraFileUploadParams : {
                        'csrfmiddlewaretoken':'{{ csrf_token }}'
                },
            });
        });
</script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/blog/home/">{{ request.user.blog.site_title }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">博客 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">文章</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">更多 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">

                {% if  request.user.is_authenticated %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">更多操作 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-lg">修改密码</a></li>
                            <li><a href="{% url 'login' %}">退出登录</a></li>
                            <li><a href="{% url 'set_avatar' %}">修改头像</a></li>
                            <li><a href="{% url 'backend' %}">后台管理</a></li>
                        </ul>
                        {#<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Large modal</button>#}

                        <div class="modal bs-example-modal-lg" tabindex="-1" role="dialog"
                             aria-labelledby="myLargeModalLabel">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                    <h1 class="text-center">修改密码</h1>
                                    <div class="row">
                                        <div class="col-md-8 col-md-offset-2">
                                            <div class="form-group"><label for="">当前用户：<input type="text"
                                                                                              disabled
                                                                                              value="{{ request.user.username }}"
                                                                                              class="form-control"></label>
                                            </div>
                                            <div class="form-group"><label for="">原始密码:<input type="password"
                                                                                              name="old_password"
                                                                                              id="id_old_password"
                                                                                              class="form-control"></label>
                                            </div>
                                            <div class="form-group"><label for="">新的密码 <input type="password"
                                                                                              name="new_password"
                                                                                              id="id_new_password"
                                                                                              class="form-control"></label>
                                            </div>
                                            <div class="form-group"><label for="">确认密码<input type="password"
                                                                                             name="confirm_password"
                                                                                             id="id_confirm_password"
                                                                                             class="form-control"></label>
                                            </div>
                                            <button class="btn btn-danger pull-right" style="" id="id_edit">修改</button>
                                            <button type="button" id="myButton" class="btn btn-success pull-left">取消
                                            </button>
                                            <span style="color: red" id="error"></span>
                                            <br>
                                            <br>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                {% else %}
                    <li style="margin-right: 50px; font-size: 20px"><a href="{% url 'register' %}">注册</a></li>
                    <li style="margin-right: 50px; font-size: 20px"><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                               aria-expanded="true" aria-controls="collapseOne">
                                更多操作
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="/blog/add_article">添加文章</a>
                        </div>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="">添加随笔</a>
                        </div>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="">草稿箱</a>
                        </div>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="">其他</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"
                                                              data-toggle="tab">文章</a></li>
                    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab"
                                               data-toggle="tab">随笔</a>
                    </li>
                    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab"
                                               data-toggle="tab">草稿</a>
                    </li>
                    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab"
                                               data-toggle="tab">设置</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        {% block article %}
                        
                        {% endblock %}
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">随笔页面</div>
                    <div role="tabpanel" class="tab-pane" id="messages">草稿页面</div>
                    <div role="tabpanel" class="tab-pane" id="settings">设置页面</div>
                </div>

            </div>
        </div>
    </div>
</div>
</body>
</html>